
services:
  # ----------------------------------------
  # MySQL
  # ----------------------------------------
  mysql:
    image: mysql:8.0
    container_name: beyou-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beyou
      MYSQL_USER: beyou
      MYSQL_PASSWORD: beyou123
    ports:
    - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  # ----------------------------------------
  # MongoDB
  # ----------------------------------------
  mongo:
    image: mongo:7
    container_name: beyou-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: beyou
      MONGO_INITDB_ROOT_PASSWORD: beyou123
      MONGO_INITDB_DATABASE: beyou
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  # ----------------------------------------
  # Backend FastAPI
  # ----------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beyou-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # MongoDB
      MONGO_URI: mongodb+srv://joaovitorcleto129_db_user:26052010o@cluster0.rb0y6ys.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGO_DB: beyou

      # MySQL
      MYSQL_HOST: beyou-mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Jo@26052010
      MYSQL_DB: beyou

      # App
      APP_NAME: BeYou - FastAPI
      PORT: 8000
      REACT_APP_API_URL: http://localhost:8000
    volumes:
      - ./app:/app/app:rw
    depends_on:
      mongo:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # ----------------------------------------
  # Frontend React
  # ----------------------------------------
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: beyou-frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "8888:8080"

# ----------------------------------------
# Volumes persistentes
# ----------------------------------------
volumes:
  mongo_data:
    driver: local
  mysql_data:
    driver: local
